//Array com frases para o bot twittar
const frases = [
    'faz frio em sao paulo',
    'o que é o que é',
    'clara e salgada',
    'tem sabor de mar',
    'jesus chorou',
    'irmã do desespero',
    'rival da esperança',
    'amante do drama',
    'vem pra minha cama',
    'o barato é louco',
    'o processo é lento',
    'o que adianta eu ser durão e o coração ser vulnerável?',
    'é quente',
    'só...',
    'verme sai da reta',
    'tá bom',
    'não vai pra grupo, irmão',
    'jesus chorou',
    'porra, vagabundo',
    'to chapando',
    'eta mundo bom de acabar',
    'muita calma ladrão',
    'nada como um dia após o outro dia',
    'durmo mal',
    'sensação de mágoa e rancor',
    'que horas são?',
    'fumaça vai, fumaça vem',
    'ficou loco',
    'tipo o que?',
    'esse brown aí é cheio de querer ser',
    'vamo ve se é isso tudo quando ver as quadrada',
    'só pensa nele memo',
    'tudo pelas verde',
    'vão me chamar de senhor, não por vulgo',
    'eu não pago pau pra ninguém',
    'quem tem boca fala o que quer pra ter nome',
    'não entende a dor e as lágrima do palhaço',
    'pensa no futuro que isso é ilusão',
    'po mãe',
    'dinheiro é bom',
    'judas incolor',
    'cadê meu sorriso?',
    'Lágrimas',
    'sozinho eu sou agora o meu inimigo íntimo',
    'sozinho penso merda pra carai',
    'Che Guevara',
    'Malcom X',
    'Não joga pérola aos porco irmão',
    'eu sei, você sabe o que é frustração',
    'famoso pra carai',
    'rasgar as madrugada só de 1100',
    'Filho meu, não inveje o homem violento e nem siga nenhum dos seus caminhos',
    'Chora agora ri depois',
    'firmeza total',
    'mais um ano se passando',
    'muita coletividade na quebrada',
    'dinheiro no bolso, sem miséria',
    'vamo brindar o dia de hoje que o amanha só pertence a Deus',
    'a vida é loka',
    'xô fala p ce:',
    'tudo vai tudo é fase',
    'logo mais vamo arrebentar no mundão',
    'champagne para o ar',
    'pobre é o diabo',
    'pode rir',
    'ri mas não desacredita não',
    'é só questão de tempo o fim do sofrimento',
    'um brinde pros guerreiro',
    'zé povinho eu lamento',
    'vermes que só faz peso na Terra',
    'tira o zoio',
    'vê se me erra'
];

module.exports = frases    //Exportando o array para ser utilizado em outro arquivo